/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dao;

import beansEx2.Aluno;
import beansEx2.Professor;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ConsultarEscola extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarEscola
     */
    public ConsultarEscola() {
        initComponents();
    }
    
    private void limparFormulario(){
        txtId.setText("");
        txtNome.setText("");
        btnGroupTipo.clearSelection();
        txtIdade.setText("");
        cmbCursoDisciplina.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        lblIdFixo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtIdFixo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblIdade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCursoDisc = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cmbCursoDisciplina = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        txtIdade = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        rdAluno = new javax.swing.JRadioButton();
        rdProfessor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdFixo.setText("ID:");

        lblId.setText("ID:");

        txtIdFixo.setEditable(false);

        lblNome.setText("Nome:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblIdade.setText("Idade:");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar e Excluir Pessoa");

        lblCursoDisc.setText("Curso/Disciplina:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        cmbCursoDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computação", "Biologia", "Agronomia", "Engenharia Mecânica", "Med. Veterinária", "Pedagogia", "Desenvolvimento de Software", "Geografia Espacial" }));
        cmbCursoDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoDisciplinaActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo:");

        btnGroupTipo.add(rdAluno);
        rdAluno.setText("Aluno");
        rdAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlunoActionPerformed(evt);
            }
        });

        btnGroupTipo.add(rdProfessor);
        rdProfessor.setText("Professor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblIdFixo)
                                    .addComponent(lblTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCursoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblCursoDisc)
                                            .addGap(269, 269, 269))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIdade)
                                            .addGap(101, 101, 101)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAtualizar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdAluno)
                                            .addGap(58, 58, 58)
                                            .addComponent(rdProfessor))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(75, 75, 75)
                                            .addComponent(btnConsultar))))))
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtId, txtIdFixo, txtIdade});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rdAluno)
                    .addComponent(rdProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFixo)
                    .addComponent(txtIdFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCursoDisc)
                    .addComponent(cmbCursoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       if(rdAluno.isSelected()){
            Aluno a = new Aluno();
            a.setId(Integer.parseInt(txtIdFixo.getText()));
            a.setNome(txtNome.getText());
            a.setIdade(Integer.parseInt(txtIdade.getText()));
            a.setCurso(cmbCursoDisciplina.getSelectedItem().toString());
            System.out.println("Aluno atualizado!");

            AlunoDAO aDAO = new AlunoDAO();
            aDAO.editar(a);
            limparFormulario();
        }
        else if(rdProfessor.isSelected()){
            Professor po = new Professor();
            po.setId(Integer.parseInt(txtIdFixo.getText()));
            po.setNome(txtNome.getText());
            po.setIdade(Integer.parseInt(txtIdade.getText()));
            po.setDisciplina(cmbCursoDisciplina.getSelectedItem().toString());
            System.out.println("Professor atualizado!");

            ProfessorDAO poDAO = new ProfessorDAO();
            poDAO.editar(po);
            limparFormulario();
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            if(rdAluno.isSelected()){
                AlunoDAO aDAO = new AlunoDAO();
                aDAO.excluir(Integer.parseInt(txtIdFixo.getText()));
                limparFormulario();
            } else if(rdProfessor.isSelected()){
                ProfessorDAO poDAO = new ProfessorDAO();
                poDAO.excluir(Integer.parseInt(txtIdFixo.getText()));
                limparFormulario();
            }
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cmbCursoDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoDisciplinaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (rdAluno.isSelected()){
            int idAluno = Integer.parseInt(txtId.getText());
            AlunoDAO aDAO = new AlunoDAO();
            
            Aluno a = aDAO.getAluno(idAluno);
            if(a == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Aluno não encontrado!");
            }
            else{
                txtId.setText(a.getId() + "");
                txtNome.setText(a.getNome());
                txtIdade.setText(a.getIdade() + "");
                cmbCursoDisciplina.setSelectedItem(a.getCurso());
            }    
        }
        else if (rdProfessor.isSelected()){
            int idProfessor = Integer.parseInt(txtId.getText());
            ProfessorDAO poDAO = new ProfessorDAO();
            
            Professor po = poDAO.getProfessor(idProfessor);
            if(po == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Professor não encontrado!");
            }
            else{
                txtId.setText(po.getId() + "");
                txtNome.setText(po.getNome());
                txtIdade.setText(po.getIdade() + "");
                cmbCursoDisciplina.setSelectedItem(po.getDisciplina());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void rdAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAlunoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarEscola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JComboBox<String> cmbCursoDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCursoDisc;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdFixo;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rdAluno;
    private javax.swing.JRadioButton rdProfessor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdFixo;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
