/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conexao;

import dao.ConsultarEscola;
import dao.RelatorioAlunos;
import dao.RelatorioProfessores;

/**
 *
 * @author laboratorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        MnArquivo = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();
        MnCadastro = new javax.swing.JMenu();
        cadEscola = new javax.swing.JMenuItem();
        editEscola = new javax.swing.JMenuItem();
        MnRelatorios = new javax.swing.JMenu();
        RelAlunos = new javax.swing.JMenuItem();
        RelProfessores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnArquivo.setText("Arquivo");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        MnArquivo.add(sair);

        jMenuBar2.add(MnArquivo);

        MnCadastro.setText("Cadastro");

        cadEscola.setText("Cadastro de Alunos/Professores");
        cadEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEscolaActionPerformed(evt);
            }
        });
        MnCadastro.add(cadEscola);

        editEscola.setText("Editar e excluir Alunos/Professores");
        editEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEscolaActionPerformed(evt);
            }
        });
        MnCadastro.add(editEscola);

        jMenuBar2.add(MnCadastro);

        MnRelatorios.setText("Relatórios");

        RelAlunos.setText("Relatório de Alunos");
        RelAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelAlunosActionPerformed(evt);
            }
        });
        MnRelatorios.add(RelAlunos);

        RelProfessores.setText("Relatório de Professores");
        RelProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelProfessoresActionPerformed(evt);
            }
        });
        MnRelatorios.add(RelProfessores);

        jMenuBar2.add(MnRelatorios);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEscolaActionPerformed
        ConsultarEscola editEscola = new ConsultarEscola();
        editEscola.setVisible(true);
    }//GEN-LAST:event_editEscolaActionPerformed

    private void cadEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEscolaActionPerformed
        CadastroEscola cadEscola = new CadastroEscola();
        cadEscola.setVisible(true);
    }//GEN-LAST:event_cadEscolaActionPerformed

    private void RelAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelAlunosActionPerformed
        RelatorioAlunos relAluno = new RelatorioAlunos();
        relAluno.setVisible(true);
    }//GEN-LAST:event_RelAlunosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void RelProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelProfessoresActionPerformed
        RelatorioProfessores relProfessores = new RelatorioProfessores();
        relProfessores.setVisible(true);
    }//GEN-LAST:event_RelProfessoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnArquivo;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenu MnRelatorios;
    private javax.swing.JMenuItem RelAlunos;
    private javax.swing.JMenuItem RelProfessores;
    private javax.swing.JMenuItem cadEscola;
    private javax.swing.JMenuItem editEscola;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
